#! /bin/bash

do_commit () {
  git config user.name "Brian Skinn"
  git config user.email "brian.skinn@gmail.com"

  git add . && git commit -m "Commit feed - $( date -uIs )"
  
  if [[ $? -eq 0 ]]
  then
    git push
  fi

  # Keep the prior 'master' up to date with 'main' to avoid
  # breaking existing subscribers
  git checkout master && git reset --hard main && git push -f

}

if [[ $TRIGGER = "schedule" ]]
then
  do_commit
  exit 0
fi

if [[ $TRIGGER = "workflow_dispatch" && $COMMIT_OPTION = "true" ]]
then
  do_commit
  exit 0
fi

echo "No commit, wrong conditions"
