#! /bin/bash

do_commit () {
  git config user.name "Brian Skinn"
  git config user.email "brian.skinn@gmail.com"

  git add . && git commit -m "Commit feed - $( date -uIs )"

  if [[ $? -eq 0 ]]
  then
    git push
  fi

  # Keep the prior 'master' up to date with 'main' to avoid
  # breaking existing subscribers
  if [[ -n $( git branch | grep '*' | grep -E '^\s*[*]\s+main\s*$' ) ]]; then
    echo "Updating master to be even with main..."
    git checkout master && git reset --hard main && git push -f
  else
    echo "Not on main, skipping update of master"
  fi

}

if [[ $TRIGGER = "schedule" ]]
then
  do_commit
  exit 0
fi

if [[ $TRIGGER = "workflow_dispatch" && $COMMIT_OPTION = "true" ]]
then
  do_commit
  exit 0
fi

echo "No commit, wrong conditions"
