#! /bin/bash

do_commit () {
  git config user.name "Brian Skinn"
  git config user.email "brian.skinn@gmail.com"

  if [[ $AMEND_OPTION = "Y" ]]
  then
    $AMEND_FLAG=--amend
    $FORCE_FLAG=-f
  else
    $AMEND_FLAG=
    $FORCE_FLAG=
  fi

  git add . && git commit -m "Commit test log - $( date -uIs )" $AMEND_FLAG
  
  if [[ $? -eq 0 ]]
  then
    git push
  fi
}

if [[ $TRIGGER = "schedule" ]]
then
  export AMEND_OPTION=Y
  do_commit
  exit 0
fi

if [[ $TRIGGER = "workflow_dispatch" && $COMMIT_OPTION = "Y" ]]
then
  do_commit $FORCE_FLAG
  exit 0
fi

echo "No commit, wrong conditions"
