[tox]
minversion=2.0
isolated_build=True
envlist=
    black
    zizmor

[testenv:black]
description=Autoformat code and tests with black
skip_install=True
deps=black
commands=
    black --version
    black {posargs} .

[testenv:zizmor]
description=Lint GitHub Actions
skip_install=True
deps=zizmor
commands=
    zizmor --version
    zizmor {posargs} .
